### ISSUE TITLE
Z_BUF_ERROR makes app crash

### ISSUE THREAD

**Issue by romainbraun** [jacktuck/unfurl#34]
When trying to unfurl certain URLs, zlib sometimes throw a Z_BUF_ERROR, and this part of the app makes it crash.
```
res.body.once('error', (err) => {
      log('error', err.message)

      process.nextTick(function () {
        throw err
      })
    })

```
I was using this URL `https://www.reddit.com/r/holdmybeer/comments/9644ap/work_is_hard/`

The result of the unfurling is fine but the app crashes. Should an error really be thrown in the case of that non fatal error?

**Comment by romainbraun** [comment]
1.1.7

**Comment by jacktuck** [comment]
I can replicate very occasionally but seems like i did have some metadata when the error is thrown, so it shouldn't be a fatal error, i'll make a prerelease on npm if you wouldn't mind seeing if it solves the issue in version`1.1.8-beta.3`

**Comment by romainbraun** [comment]
Thank you very much for your quick reaction. Giving it a try today!

**Comment by romainbraun** [comment]
Looking great, I can't seem to be able to reproduce so far.

**Comment by jacktuck** [comment]
@romainbraun No problem, glad it works for you now 😃
