### ISSUE TITLE
Exports no types for Typescript

### ISSUE THREAD

**Issue by dimroc** [jacktuck/unfurl#42]
When using `unfurl` like so, it leads to a complaint by typescript:

```typescript
import unfurl = require("unfurl.js")
const unfurled = unfurl(last)
```

```
2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/Users/dimroc/go/src/github.com/dimroc/storyboard/functions/node_modules/unfurl.js/dist/index")' has no compatible call signatures
```

This is probably because we don't export types:
https://github.com/jacktuck/unfurl/blob/master/dist/index.d.ts

```
export {};
```

Let me know if I'm missing an easy step.

**Comment by jacktuck** [comment]
I've not tested but i think you've got your import wrong.

`import unfurl from "unfurl.js"` or  `const unfurl = require("unfurl.js")`

**Comment by dimroc** [comment]
Thanks for the quick response @jacktuck.
1. `import unfurl from "unfurl.js"` has the same issue
2. `const unfurl = require("unfurl.js")` works and is what I've ended up doing as a stopgap, but this doesn't import the type into the typescript world, it bypasses the type definition.

**Comment by jacktuck** [comment]
@dimroc Forgot to say. This should now be fixed :)
