### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by atjeff** [jacktuck/unfurl#59]
I was having a hard time finding the actual npm package as there isn't an installation section in the readme, and the npm badge doesn't actually link to the package. Which got me curious and digging through the readme. Why was the installation section removed? Do you need a PR to add it back?

**Comment by jacktuck** [comment]
Sure, open to adding it back. I figured people would deduce it from
```
import { unfurl } from 'unfurl.js'
```

or the "name" in package.json
