### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by wereHamster** [jacktuck/unfurl#63]
It would be nice if the returned metadata included links to the favicon. Do you think such a feature is in scope of this package?

**Comment by jacktuck** [comment]
We should already be returning the favicon - so maybe the code for doing so needs tweaking. 

https://github.com/jacktuck/unfurl/blob/76cab79ec1fbc02e9e3e2e928d224c4c52b8a26b/src/index.ts#L195

Do you have an example where the favicon is not being picked up?

**Comment by wereHamster** [comment]
I was not looking at the source code, I was looking at the Metadata type that is described in the readme, which does not mention the favicon. The favicon is indeed being extracted correctly in the few tests I did.

Maybe the readme can link directly to the TypeScript Metadata type in the source code instead of repeating it?
