### ISSUE TITLE
Add semantic releases

### ISSUE THREAD

**Issue by jacktuck** [jacktuck/unfurl#65]
https://semantic-release.gitbook.io/

**Comment by jacktuck** [comment]
We now have semantic release running.

**Comment by trieloff** [comment]
With Semantic Release set up, you might want to try this GitHub action we are using in Helix: https://github.com/adobe/helix-embed/blob/master/.github/workflows/semver-check.yaml

It will leave a comment like this https://github.com/adobe/helix-embed/pull/345#issuecomment-739253429 for every PR to tell you about the release impact, which makes it easy to spot breaking changes or mislabeled changes.
