### ISSUE TITLE
Incorrect metadata types

### ISSUE THREAD

**Issue by henrykuzmick** [jacktuck/unfurl#73]
Hey 👋 
Thanks for the great lib!
The `Metadata` type defines `twitter_card` and `open_graph` as arrays, but the received results are objects.

**Comment by jacktuck** [comment]
Hey Henry!

I've just had a look and you're right! 🤦 . Sorry, not quite sure how this went unnoticed (by me). Anyway, would you like to submit a PR for the fix? If not I'll take a look in the morning.

**Comment by henrykuzmick** [comment]
Sure, I'll try to ping you with a PR sometime tomorrow 👌
