### ISSUE TITLE
Add support article type in OGP specification

### ISSUE THREAD

**Issue by fuji44** [jacktuck/unfurl#80]
Hi all.

I'm looking to support the article type as written in the OGP [specification](https://ogp.me/#type_article).
The specification has the following description.

> These are globally defined objects that just don't fit into a vertical but yet are broadly used and agreed upon.

I interpreted this as "not specified as an OGP, but widely used".
I thought that some people might not like to support it with unfurl, depending on their interpretation of this statement.

Do you guys have any doubts about being able to handle article types in unfurl?
If there is no doubt, I'd like to start working on it.

**Comment by jacktuck** [comment]
Hey @fuji44. I don't see any problem with us supporting this 👍

**Comment by fuji44** [comment]
Thanks for the answer. I would like to work on this in my spare time.
