### ISSUE TITLE
[Bug]: SoundCloud oEmbed is not returning any html content

### ISSUE THREAD

**Issue by adrian-seijo** [jacktuck/unfurl#97]
PR: https://github.com/jacktuck/unfurl/pull/96

I was playing around with SoundCloud urls on `unfurl` and I noticed that they don't return any html content currently while they do for other attributes. 

The issue seems to be that they are escaping the html content with a `CDATA` and that trips the logic that extracts the content.

I have [raised a PR](https://github.com/jacktuck/unfurl/pull/96) that will fix that by checkign for that scenario and clearing that `CDATA`. 

Hopefully that will solve the issue, feel free to close this if you consider it irrrelevant sicne we have a PR but I just wanted to leave something written on an issue in case someone comes in the future asking why this was done :D

**Comment by jacktuck** [comment]
Fixed in #98. Thanks Adrian!
